package module.evolview.phylotree.visualization.graphics.struct;

public enum TreeLayout {

	SLOPE_CLADO_ALIGNED_LEFT,

	RECT_CLADO_ALIGNED_LEFT,

	RECT_CLADO_EQUAL_LEFT, 

	RECT_INNER_YAXIS,

	RECT_PHYLO_LEFT,
	
	RECT_PHYLO_ALIGN2TIP,
	RECT_HALF_CIRCLE,

	INNER_CIR_CLADO, OUTER_CIR_CLADO_ALIGNED, OUTER_CIR_PHYLO,OUTER_CIR_PHYLO_ALIGNED,OUTER_CIR_CLADO_EQUAL,
	
	SPRIAL_ALPHA_PHYLO, SPRIAL_ALPHA_CLADO,

	SPRIAL_BETA_PHYLO, SPRIAL_BETA_CLADO,
	
	RADIAL_CLADO, RADIAL_PHYLO, RADIAL_EQUAL_DAYLIGHT_PHYLO, RADIAL_EQUAL_DAYLIGHT_CLADO;

}
